### this is a function file created to match the clinical_data_extract_DW.R file
### input files required: needs the results.master (RDS) which is generated by the clinPathAssess function


extractKM <- function(results.master, subset.index){
  pval <- lapply(results.master, function(x){return(x[[1]][[subset.index]][[1]])}) 
  pval <- do.call(rbind, pval)
  adj.pval <-p.adjust(pval, method = "BH") 
  temp.return <- cbind(pval, adj.pval)
  colnames(temp.return) <- c("pval", "adj.pval")
  return(temp.return)
}


cox.dataframe <- function(pval, Zscore, HR, L95CI, U95CI){
  cox.pval.assembled <- do.call(rbind, pval)
  adj.cox.pval <- p.adjust(cox.pval.assembled, method = "BH")
  #cox.pval.combined.df <- cbind(cox.pval.assembled, adj.cox.pval)
  #colnames(cox.pval.combined.df)<-c("cox.pval", "cox.adj.pval")
  cox.Zscore.assembled <- do.call(rbind, Zscore)
  cox.HR.assembled <- do.call(rbind, HR)
  cox.L95CI.assembled <- do.call(rbind, L95CI)
  cox.U95CI.assembled <- do.call(rbind, U95CI)
  cox.allresults.df <- cbind(cox.pval.assembled, adj.cox.pval, cox.Zscore.assembled, cox.HR.assembled, cox.L95CI.assembled, cox.U95CI.assembled)
  colnames(cox.allresults.df)<- c("cox.pval", "cox.adj.pval", "cox.Zscore","cox.HR", "cox.HR.L95CI", "cox.HR.U95CI" )
  return (cox.allresults.df)
}


extract.cox.pval<- function (x, subset.index){
  return(ifelse(length(x[[4]])< 4, NA,  ### changed from < 3 (9/10/17), check i=25
                ifelse(length(x[[4]][[subset.index]])<1, NA, ### changed from < 6  (9/10/17), still does not work
                       ifelse(length(x[[4]][[subset.index]][[1]])<1, NA,
                              x[[4]][[subset.index]][[1]]))))
}

extract.cox.Zscore <- function(x, subset.index){
  return(ifelse(length(x[[4]])<4, NA,    ### changed from < 3 (9/10/17)
                ifelse(length(x[[4]][[subset.index]])<6, NA, 
                       ifelse(length(x[[4]][[subset.index]][[5]])<1, NA,
                              x[[4]][[subset.index]][[5]]))))
}


extract.cox.HR <- function(x, subset.index){
  ifelse(length(x[[4]])<4, NA,  ### 9/10/17 update:  was < 3, works for all values 4, 5, 6
         ifelse(length(x[[4]][[subset.index]])<6, NA, 
                ifelse(length(x[[4]][[subset.index]][[2]])<1, NA,
                       x[[4]][[subset.index]][[2]])))
}

extract.cox.L95CI.HR <- function(x, subset.index){
  ifelse(length(x[[4]])<4, NA,  ### 9/10/17 update:  was < 3, works for all values 4, 5, 6
         ifelse(length(x[[4]][[subset.index]])<6, NA,  ### original script has <4 for this parameter, updated 5/10/17. ### 12109 is where the error is occurring
                ifelse(length(x[[4]][[subset.index]][[3]])<1, NA,
                       x[[4]][[subset.index]][[3]])))
}

extract.cox.U95CI.HR <- function(x, subset.index){
  return(ifelse(length(x[[4]]) < 4, NA,  ### 9/10/17 update:  was < 3, works 
                ifelse(length(x[[4]][[subset.index]])<6, NA, ### changed from <4, to < 6. May need to alter for other RDS input file
                       ifelse(length(x[[4]][[subset.index]][[4]])<1, NA, ### updated
                              x[[4]][[subset.index]][[4]]))))
}

extract.cox <- function(results.master, subset.index){
  cox.dataframe(pval = lapply(results.master, extract.cox.pval, subset.index = subset.index),
                Zscore = lapply(results.master, extract.cox.Zscore, subset.index = subset.index),
                HR = lapply(results.master, extract.cox.HR, subset.index = subset.index),
                L95CI = lapply (results.master, extract.cox.L95CI.HR, subset.index = subset.index),
                U95CI = lapply(results.master, extract.cox.U95CI.HR, subset.index = subset.index)
  )
}
