### this is a function file created to match the clinical_data_extract_DW.R file
### input files required: needs the results.master (RDS) which is generated by the clinPathAssess function

### names of functions
### extract.km.OS.pval
### extract.km.EFS.pval
### extract.km.PFS.pval
### cox.dataframe
### extract.cox.pval
### extract.cox.pval.SHH.old
### extract.cox.Zscore
### extract.cox.Zscore.SHH.old
### extract.cox.HR
### extract.cox.HR.SHH.old
### extract.cox.L95CI.HR
### extract.cox.L95CI.SHH.old
### extract.cox.U95CI.SHH.old
### extract.cox.U95CI.SHH.old
### log.reg.dataframe

#####################################################################################
### km.OS
extract.km.OS.pval <- function(results.master, name){
  extracted.km.OS.pval <- lapply(results.master, function(x){return(x[["surv.p.values.list"]][[name]][["OS.p.val"]])}) 
  km.OS.p.extract.assembled <- do.call(rbind, extracted.km.OS.pval)
  adjusted.p.km.OS<-p.adjust(km.OS.p.extract.assembled, method = "BH") 
  OS.pvalue <- cbind(km.OS.p.extract.assembled, adjusted.p.km.OS)
  colnames(OS.pvalue) <- c("OS.p.value", "OS.adjusted.pval")
  return(OS.pvalue)
} 

### km.EFS
extract.km.EFS.pval <- function(results.master, name){
  extracted.km.EFS.pval<- lapply(results.master, function(x){return(x[["surv.p.values.list"]][[name]][["EFS.p.val"]])}) 
  km.EFS.p.extract.assembled <- do.call(rbind, extracted.km.EFS.pval)
  adjusted.p.km.EFS <-p.adjust(km.EFS.p.extract.assembled, method = "BH") 
  EFS.pvalue <- cbind(km.EFS.p.extract.assembled, adjusted.p.km.EFS)
  colnames(EFS.pvalue) <- c("EFS.p.value", "EFS.adjusted.pval")
  return(EFS.pvalue)
} 

### km.PFS
extract.km.PFS.pval <- function(results.master, name){
  extracted.km.PFS.pval<- lapply(results.master, function(x){return(x[["surv.p.values.list"]][[name]][["PFS.p.val"]])}) 
  km.PFS.p.extract.assembled <- do.call(rbind, extracted.km.PFS.pval)
  adjusted.p.km.PFS <-p.adjust(km.PFS.p.extract.assembled, method = "BH") 
  PFS.pvalue <- cbind(km.PFS.p.extract.assembled, adjusted.p.km.PFS)
  colnames(PFS.pvalue) <- c("PFS.p.value", "PFS.adjusted.pval")
  return(PFS.pvalue)
} 


###
cox.dataframe <- function(pval, Zscore, HR, L95CI, U95CI){
  cox.pval.assembled <- do.call(rbind, pval)
  adj.cox.pval <- p.adjust(cox.pval.assembled, method = "BH")
  #cox.pval.combined.df <- cbind(cox.pval.assembled, adj.cox.pval)
  #colnames(cox.pval.combined.df)<-c("cox.pval", "cox.adj.pval")
  cox.Zscore.assembled <- do.call(rbind, Zscore)
  cox.HR.assembled <- do.call(rbind, HR)
  cox.L95CI.assembled <- do.call(rbind, L95CI)
  cox.U95CI.assembled <- do.call(rbind, U95CI)
  cox.allresults.df <- cbind(cox.pval.assembled, adj.cox.pval, cox.Zscore.assembled, cox.HR.assembled, cox.L95CI.assembled, cox.U95CI.assembled)
  colnames(cox.allresults.df)<- c("cox.pval", "cox.adj.pval", "cox.Zscore","cox.HR", "cox.HR.L95CI", "cox.HR.U95CI" )
  return (cox.allresults.df)
}


extract.cox.pval<- function (x, subset.index){
  return(ifelse(length(x[[4]])< 4, NA,  ### changed from < 3 (9/10/17), check i=25
                ifelse(length(x[[4]][[subset.index]])<1, NA, ### changed from < 6  (9/10/17)
                       ifelse(length(x[[4]][[subset.index]][[1]])<1, NA,
                              x[[4]][[subset.index]][[1]]))))
}


extract.cox.pval.SHH.old <- function (x, subset.index){
  return(ifelse(length(x[[4]])< 17, NA, ###  used to be 10. Change to <15, then < 17. works with length < 3 and < 4 above for PFS for all groups, change it to 10 for it to work for G3G4 PFS 11/10/17
                ifelse(length(x[[4]][[subset.index]])<6, NA, 
                       ifelse(length(x[[4]][[subset.index]][[1]])<1, NA,
                              x[[4]][[subset.index]][[1]]))))
}
  


extract.cox.Zscore <- function(x, subset.index){
  return(ifelse(length(x[[4]])<4, NA,    ### changed from < 3 (9/10/17)
                ifelse(length(x[[4]][[subset.index]])<6, NA, 
                       ifelse(length(x[[4]][[subset.index]][[5]])<1, NA,
                              x[[4]][[subset.index]][[5]]))))
}


extract.cox.Zscore.SHH.old <- function(x, subset.index){
  return (ifelse(length(x[[4]])<17, NA,
                 ifelse(length(x[[4]][[subset.index]])<6, NA,
                        ifelse(length(x[[4]][[subset.index]][[5]])<1, NA, 
                               x[[4]][[subset.index]][[5]]))))
}



extract.cox.HR <- function(x, subset.index){
  ifelse(length(x[[4]])<4, NA,  ### 9/10/17 update:  was < 3, works for all values 4, 5, 6
         ifelse(length(x[[4]][[subset.index]])<6, NA, 
                ifelse(length(x[[4]][[subset.index]][[2]])<1, NA,
                       x[[4]][[subset.index]][[2]])))
}


extract.cox.HR.SHH.old <- function (x, subset.index){
  return(ifelse(length(x[[4]])< 17, NA, 
                ifelse(length(x[[4]][[subset.index]])<6, NA, 
                       ifelse(length(x[[4]][[subset.index]][[2]])<1, NA,
                              x[[4]][[subset.index]][[2]]))))
}


extract.cox.L95CI.HR <- function(x, subset.index){
  ifelse(length(x[[4]])<4, NA,  ### 9/10/17 update:  was < 3, works for all values 4, 5, 6
         ifelse(length(x[[4]][[subset.index]])<6, NA,  ### original script has <4 for this parameter, updated 5/10/17. ### 12109 is where the error is occurring
                ifelse(length(x[[4]][[subset.index]][[3]])<1, NA,
                       x[[4]][[subset.index]][[3]])))
}


extract.cox.L95CI.SHH.old <- function(x, subset.index){
  return (ifelse(length(x[[4]])<17, NA,
                 ifelse(length(x[[4]][[subset.index]])<6, NA,
                        ifelse(length(x[[4]][[subset.index]][[3]])<1, NA, 
                               x[[4]][[subset.index]][[3]]))))
}

extract.cox.U95CI.HR <- function(x, subset.index){
  return(ifelse(length(x[[4]]) < 4, NA,  ### 9/10/17 update:  was < 3, works 
                ifelse(length(x[[4]][[subset.index]])<6, NA, ### changed from <4, to < 6. May need to alter for other RDS input file
                       ifelse(length(x[[4]][[subset.index]][[4]])<1, NA, ### updated
                              x[[4]][[subset.index]][[4]]))))
}


extract.cox.U95CI.SHH.old <- function(x, subset.index){
  return (ifelse(length(x[[4]])<17, NA,
                 ifelse(length(x[[4]][[subset.index]])<6, NA,
                        ifelse(length(x[[4]][[subset.index]][[4]])<1, NA, 
                               x[[4]][[subset.index]][[4]]))))
}




######################################################################

extract.cox <- function(results.master, subset.index){
  cox.dataframe(pval = lapply(results.master, extract.cox.pval, subset.index = subset.index),
                Zscore = lapply(results.master, extract.cox.Zscore, subset.index = subset.index),
                HR = lapply(results.master, extract.cox.HR, subset.index = subset.index),
                L95CI = lapply (results.master, extract.cox.L95CI.HR, subset.index = subset.index),
                U95CI = lapply(results.master, extract.cox.U95CI.HR, subset.index = subset.index)
  )
}




extract.cox.SHH.old <- function (results.master, subset.index){
   cox.dataframe(pval = lapply(results.master, extract.cox.pval.SHH.old, subset.index=subset.index),
                 Zscore = lapply (results.master, extract.cox.Zscore.SHH.old, subset.index=subset.index),
                 HR = lapply(results.master, extract.cox.HR.SHH.old, subset.index=subset.index),
                 L95CI = lapply(results.master, extract.cox.L95CI.SHH.old, subset.index=subset.index),
                 U95CI = lapply(results.master, extract.cox.U95CI.SHH.old, subset.index=subset.index)
    )
 }
 
 

######################################################################


 extract.cox.OS <- function(results.master, subset.index){
 cox.dataframe (pval = lapply(results.master, extract.cox.OS.pval, subset.index = subset.index), 
               Zscore = lapply (results.master, extract.cox.OS.Zscore, subset.index = subset.index),
               HR = lapply(results.master, extract.cox.OS.HR,subset.index = subset.index ),
               L95CI = lapply (results.master, extract.cox.OS.L95CI, subset.index = subset.index),
               U95CI = lapply(results.master, extract.cox.OS.U95CI,subset.index = subset.index )
  )               
 }



########################################

### creating cox OS function with subsets < 5, < 6, <1
### 17/10/17:have had to increase the subsetting for subsequent cox OS dataframes
### currently (> 11 worked for extract.cox.OS to work for cox.OS.cat, then  > 12 needed for cox.OS.cont, then  x[[4]]>13 (increasing each time)needed for cox.OS.cat.G3G4, then > 14 needed for cox.OS.cont.G3G4, now up to 14 

extract.cox.OS.pval <-  function (x, subset.index){
  return(ifelse(length(x[[4]])< 14, NA, ###  works with length < 3 above for PFS for all groups, I had to change it to 11 for OS, then changed to 12 for cox.cont.OS
                ifelse(length(x[[4]][[subset.index]])<6, NA, 
                       ifelse(length(x[[4]][[subset.index]][[1]])<1, NA,
                              x[[4]][[subset.index]][[1]]))))
}


extract.cox.OS.HR <- function (x, subset.index){
  return(ifelse(length(x[[4]])< 14, NA, ###  see comment for extract.cox.OS.pval, which applies to all extract cox OS functions below
                ifelse(length(x[[4]][[subset.index]])<6, NA, 
                       ifelse(length(x[[4]][[subset.index]][[2]])<1, NA,
                              x[[4]][[subset.index]][[2]]))))
}


extract.cox.OS.Zscore <- function (x, subset.index){
  return(ifelse(length(x[[4]])< 14, NA,
                ifelse(length(x[[4]][[subset.index]])<6, NA, 
                       ifelse(length(x[[4]][[subset.index]][[5]])<1, NA,
                              x[[4]][[subset.index]][[5]]))))
}




extract.cox.OS.L95CI<- function (x, subset.index){
  return(ifelse(length(x[[4]])< 14, NA, 
                ifelse(length(x[[4]][[subset.index]])<6, NA, 
                       ifelse(length(x[[4]][[subset.index]][[3]])<1, NA,
                              x[[4]][[subset.index]][[3]]))))
}


extract.cox.OS.U95CI <- function (x, subset.index){
  return(ifelse(length(x[[4]])< 14, NA, 
                ifelse(length(x[[4]][[subset.index]])<6, NA, 
                       ifelse(length(x[[4]][[subset.index]][[4]])<1, NA,
                              x[[4]][[subset.index]][[4]]))))
}




#################

extract.multivar.cox.pval <-  function (x, subset.index){
  return(ifelse(length(x[[5]])< 1, NA, ### was 3
                ifelse(length(x[[5]][[subset.index]])< 6, NA,  ### was < 6
                       ifelse(length(x[[5]][[subset.index]][[1]])<1, NA,
                              x[[5]][[subset.index]][[1]]))))
}


extract.multivar.cox.HR <- function (x, subset.index){
  return(ifelse(length(x[[5]])< 1, NA, 
                ifelse(length(x[[5]][[subset.index]])< 6, NA, 
                       ifelse(length(x[[5]][[subset.index]][[2]])<1, NA,
                              x[[5]][[subset.index]][[2]]))))
}




extract.multivar.cox.Zscore <- function (x, subset.index){
  return(ifelse(length(x[[5]])< 1, NA,
                ifelse(length(x[[5]][[subset.index]])< 6, NA, 
                       ifelse(length(x[[5]][[subset.index]][[5]])<1, NA,
                              x[[5]][[subset.index]][[5]]))))
}



extract.multivar.cox.L95CI<- function (x, subset.index){
  return(ifelse(length(x[[5]])< 1, NA, 
                ifelse(length(x[[5]][[subset.index]])< 6, NA, 
                       ifelse(length(x[[5]][[subset.index]][[3]])<1, NA,
                              x[[5]][[subset.index]][[3]]))))
}


extract.multivar.cox.U95CI <- function (x, subset.index){
  return(ifelse(length(x[[5]])< 1, NA, 
                ifelse(length(x[[5]][[subset.index]])<6, NA, 
                       ifelse(length(x[[5]][[subset.index]][[4]])<1, NA,
                              x[[5]][[subset.index]][[4]]))))
}


### unhash here if troubleshooting with individual functions

 # results.master = results.master #
 # subset.index = 1                #

 
extract.multivar.cox <- function(results.master, subset.index){
  cox.dataframe (pval = lapply(results.master, extract.multivar.cox.pval, subset.index = subset.index), 
                 Zscore = lapply(results.master, extract.multivar.cox.Zscore, subset.index = subset.index), 
                 HR = lapply(results.master, extract.multivar.cox.HR,subset.index = subset.index ),
                 L95CI = lapply(results.master, extract.multivar.cox.L95CI, subset.index = subset.index),
                 U95CI = lapply(results.master, extract.multivar.cox.U95CI, subset.index = subset.index )
  )               
}


####################################
### if wish to check the individual function, could run cox.dataframe(pval... onwards) to create dataframe to check

extract.multivar.cox.PFS <- function(results.master, subset.index){
  cox.dataframe(pval = lapply(results.master, extract.multivar.cox.PFS.pval, subset.index = subset.index),
                Zscore = lapply(results.master, extract.multivar.cox.PFS.Zscore, subset.index = subset.index),
                HR = lapply(results.master, extract.multivar.cox.PFS.HR , subset.index = subset.index),
                L95CI = lapply (results.master, extract.multivar.cox.PFS.L95CI, subset.index = subset.index),
                U95CI = lapply(results.master, extract.multivar.cox.PFS.U95CI, subset.index = subset.index)
  )
}



### or create a new function for extract.multivar.cox.PFS based on directly naming the variable
### example: 
# extract.chi.all <- function(results.master, name){
  #extracted.chi.all.pval <- lapply(results.master, function(x){return(x[["chi.sq.list"]][[name]][["p.value"]])}) 
  #extracted.chi.all.pval.assembled <- do.call(rbind, extracted.chi.all.pval)
  #adjusted.p.chi.all <-p.adjust(extracted.chi.all.pval.assembled, method = "BH") 
  #chi.pvalue <- cbind(extracted.chi.all.pval.assembled, adjusted.p.chi.all)
  #colnames(chi.pvalue) <- c("chi.p.value", "adjusted.pval")
  #return(chi.pvalue)

### trying this here, but not quite working yet
# extract.multivar.cox.PFS.all <- function(results.master, name){
  #extracted.multivar.cox.PFS.pval <- lapply(results.master, function(x){return(x[["cox.multivar.p.values.list"]][[name]][["cox.pval"]])})
  #extracted.multivar.cox.PFS.HR <- lapply(results.master, function(x){return(x)[["cox.multivar.p.values.list"]][[name]][["cox.HR"]]})
  #extracted.multivar.cox.PFS.L95CI <- lapply(results.master, function(x){return(x)[["cox.multivar.p.values.list"]][[name]][["cox.lower.95CI"]]})
  #extracted.multivar.cox.PFS.U95CI <- lapply(results.master, function(x){return(x)[["cox.multivar.p.values.list"]][[name]][["cox.upper.95CI"]]})
  #extracted.multivar.cox.PFS.Zscore <- lapply(results.master, function(x){return(x)[["cox.multivar.p.values.list"]][[name]][["cox.Zscore"]]})
  
  ##cox.pval.assembled <- do.call(rbind(extracted.multivar.cox.PFS.pval))
  #extracted.adjusted.pval <- p.adjust(cox.pval.assembled, method = "BH")
  #extracted.multivar.cox.dataframe <- (pval = extracted.multivar.cox.PFS.pval, 
   #                     adj.p.val = extracted.adjusted.pval,
    #                    Zscore = extracted.multivar.cox.PFS.Zscore, 
     #                   HR = extracted.multivar.cox.PFS.HR, 
      #                  L95CI = extracted.multivar.cox.PFS.L95CI,
       #                 U95CI = extracted.multivar.cox.PFS.U95CI)
  #return(extracted.multivar.cox.dataframe)
#}


# trial.multi.cox.PFS.combined.cat <- extract.multivar.cox.PFS.all (results.master, name = "multivar.cox.PFS.combined.cat")
# results.master = results.master
# name = "multivar.cox.PFS.combined.cat"

  # x =1 
# subset.index = 1

#extract.multivar.cox.pval <-  function (x, subset.index){
#  return(ifelse(length(x[[5]])< 1, NA, ### was 3
#                ifelse(length(x[[5]][[subset.index]])< 6, NA,  ### was < 6
#                       ifelse(length(x[[5]][[subset.index]][[1]])<1, NA,
#                              x[[5]][[subset.index]][[1]]))))
#}


extract.multivar.cox.PFS.pval <- function(x, subset.index){
  return (ifelse(length(x[[5]])<14, NA, 
                 ifelse(length(x[[5]][[subset.index]])<3, NA, 
                        ifelse(length(x[[5]][[subset.index]][[1]])<1, NA, 
                               x[[5]][[subset.index]][[2]]))))
}


extract.multivar.cox.PFS.HR <- function (x, subset.index){
  return(ifelse(length(x[[5]])< 14, NA, ### was 3
                ifelse(length(x[[5]][[subset.index]])<3, NA, ### was 6
                       ifelse(length(x[[5]][[subset.index]][[2]])<1, NA,
                              x[[5]][[subset.index]][[2]]))))
}

extract.multivar.cox.PFS.L95CI <-  function (x, subset.index){
  return(ifelse(length(x[[5]])< 14, NA, ### was 3
                ifelse(length(x[[5]][[subset.index]])<3, NA, 
                       ifelse(length(x[[5]][[subset.index]][[3]])<1, NA,
                              x[[5]][[subset.index]][[3]]))))
}

extract.multivar.cox.PFS.U95CI <- function (x, subset.index){
  return(ifelse(length(x[[5]])< 14, NA, ### was 3
                ifelse(length(x[[5]][[subset.index]])<3, NA, 
                       ifelse(length(x[[5]][[subset.index]][[4]])<1, NA,
                              x[[5]][[subset.index]][[4]]))))
}


extract.multivar.cox.PFS.Zscore <- function (x, subset.index){
  return(ifelse(length(x[[5]])< 14, NA, ### was 3
                ifelse(length(x[[5]][[subset.index]])<6, NA, 
                       ifelse(length(x[[5]][[subset.index]][[5]])<1, NA,
                              x[[5]][[subset.index]][[5]]))))
}

##################

extract.multivar.cox.PFS.SHH <- function(results.master, subset.index){
  cox.dataframe(pval = lapply(results.master, extract.multivar.cox.PFS.SHH.pval, subset.index = subset.index),
                Zscore = lapply(results.master, extract.multivar.cox.PFS.SHH.Zscore, subset.index = subset.index),
                HR = lapply(results.master, extract.multivar.cox.PFS.SHH.HR , subset.index = subset.index),
                L95CI = lapply (results.master, extract.multivar.cox.PFS.SHH.L95CI, subset.index = subset.index),
                U95CI = lapply(results.master, extract.multivar.cox.PFS.SHH.U95CI, subset.index = subset.index)
  )
}


extract.multivar.cox.PFS.SHH.pval <- function(x, subset.index){
  return (ifelse(length(x[[5]])<16, NA,  ### increased from 14
                 ifelse(length(x[[5]][[subset.index]])<3, NA, ### where subset.index is 15
                        ifelse(length(x[[5]][[subset.index]][[1]])<1, NA, 
                               x[[5]][[subset.index]][[2]]))))
}


extract.multivar.cox.PFS.SHH.HR <- function (x, subset.index){
  return(ifelse(length(x[[5]])< 16, NA, ### was 3
                ifelse(length(x[[5]][[subset.index]])<3, NA, ### was 6
                       ifelse(length(x[[5]][[subset.index]][[2]])<1, NA,
                              x[[5]][[15]][[2]]))))
}

extract.multivar.cox.PFS.SHH.L95CI <-  function (x, subset.index){
  return(ifelse(length(x[[5]])< 16, NA, ### was 3
                ifelse(length(x[[5]][[subset.index]])<3, NA, 
                       ifelse(length(x[[5]][[subset.index]][[3]])<1, NA,
                              x[[5]][[subset.index]][[3]]))))
}

extract.multivar.cox.PFS.SHH.U95CI <- function (x, subset.index){
  return(ifelse(length(x[[5]])< 16, NA, ### was 3
                ifelse(length(x[[5]][[subset.index]])<3, NA, 
                       ifelse(length(x[[5]][[subset.index]][[4]])<1, NA,
                              x[[5]][[subset.index]][[4]]))))
}


extract.multivar.cox.PFS.SHH.Zscore <- function (x, subset.index){
  return(ifelse(length(x[[5]])< 16, NA, ### was 3
                ifelse(length(x[[5]][[subset.index]])<6, NA, 
                       ifelse(length(x[[5]][[subset.index]][[5]])<1, NA,
                              x[[5]][[subset.index]][[5]]))))
}



##############################################

### for logistic regression

log.reg.dataframe <- function(pval, OR, L95CI, U95CI){
  logreg.pval.assembled <- do.call(rbind, pval) ### check if recurrent error here when more than one input goi
  logreg.adj.pval <- p.adjust(logreg.pval.assembled, method = "BH")
  logreg.OR.assembled <- do.call(rbind, OR)
  logreg.L95CI.assembled <- do.call(rbind, L95CI)
  logreg.U95CI.assembled <- do.call(rbind, U95CI)
  logreg.allresults.df <- cbind(logreg.pval.assembled, logreg.adj.pval, logreg.OR.assembled, logreg.L95CI.assembled, logreg.U95CI.assembled)
  colnames(logreg.allresults.df)<- c("logreg.pval", "logreg.adj.pval","logreg.OR", "logreg.OR.L95CI", "logreg.OR.U95CI" )
  return (logreg.allresults.df)
}



##############################################
### function for extracting chi squared results
### this will work for all variables that have been run in chi squared test

extract.chi.all <- function(results.master, name){
  extracted.chi.all.pval <- lapply(results.master, function(x){return(x[["chi.sq.list"]][[name]][["p.value"]])}) 
  extracted.chi.all.pval.assembled <- do.call(rbind, extracted.chi.all.pval)
  adjusted.p.chi.all <-p.adjust(extracted.chi.all.pval.assembled, method = "BH") 
  chi.pvalue <- cbind(extracted.chi.all.pval.assembled, adjusted.p.chi.all)
  colnames(chi.pvalue) <- c("chi.p.value", "adjusted.pval")
  return(chi.pvalue)
} 


##############################################


### cox OS dataframe

# cox.OS.cat.all.df <- cox.dataframe(pval = cox.OS.pval.cat.all , Zscore = cox.OS.Zscore.cat.all, HR = cox.OS.HR.cat.all, L95CI = cox.L95CI.OS.HR.cat.all, U95CI = cox.U95CI.OS.HR.cat.all)
# colnames(cox.OS.cat.all.df) <- c("cox.OS.pval.cat.all", "cox.OS.adj.pval.cat.all", "cox.OS.Zscore.cat.all", "cox.OS.HR.cat.all","cox.L95CI.OS.HR.cat.all", "cox.U95CI.OS.HR.cat.all")

# significant.cox.OS.cat.all <- cox.OS.cat.all.df[which(cox.OS.cat.all.df[, 2]<0.05),]
#
# write.csv(significant.cox.OS.cat.all,  file = "/home/nmm199/R/MB_RNAseq/Clinical/clin.results/significant.cox.OS.complete.cat.all.csv")

###################
###################
### superceded function as of 4/12/17 as returns subset out of bounds error

# extractKM <- function(results.master, subset.index){
#  pval <- lapply(results.master, function(x){return(x[[1]][[subset.index]][[1]])}) 
#  pval <- do.call(rbind, pval)
#  adj.pval <-p.adjust(pval, method = "BH") 
#  temp.return <- cbind(pval, adj.pval)
#  colnames(temp.return) <- c("pval", "adj.pval")
#  return(temp.return)
# }

